version: '3'

volumes:
  postgres_volume:

services:
  storage:
    image: postgres:16.1
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - deploy/env/.env.local
    ports:
      - "${PG_PORT}:${PG_PORT}"
    command: -p ${PG_PORT}

  migrator:
    build:
      dockerfile: deploy/dockerfiles/migrator.Dockerfile
    env_file:
      - deploy/env/.env.local
    depends_on:
      - storage
    environment:
      PG_HOST: storage

  la_api:
    build:
      context: .
      dockerfile: deploy/dockerfiles/laAPI.Dockerfile
    env_file:
      - deploy/env/.env.local
    depends_on:
      - storage
    environment:
      PG_HOST: storage
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${GRPC_PORT}:${GRPC_PORT}"
    restart: on-failure