// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: warehouse.proto

package warehouse_v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WarehouseV1Client is the client API for WarehouseV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WarehouseV1Client interface {
	Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error)
	UndoReserve(ctx context.Context, in *UndoReserveRequest, opts ...grpc.CallOption) (*UndoReserveResponse, error)
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
}

type warehouseV1Client struct {
	cc grpc.ClientConnInterface
}

func NewWarehouseV1Client(cc grpc.ClientConnInterface) WarehouseV1Client {
	return &warehouseV1Client{cc}
}

func (c *warehouseV1Client) Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error) {
	out := new(ReserveResponse)
	err := c.cc.Invoke(ctx, "/warehouse_v1.WarehouseV1/Reserve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseV1Client) UndoReserve(ctx context.Context, in *UndoReserveRequest, opts ...grpc.CallOption) (*UndoReserveResponse, error) {
	out := new(UndoReserveResponse)
	err := c.cc.Invoke(ctx, "/warehouse_v1.WarehouseV1/UndoReserve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseV1Client) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, "/warehouse_v1.WarehouseV1/Release", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseV1Client) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, "/warehouse_v1.WarehouseV1/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WarehouseV1Server is the server API for WarehouseV1 service.
// All implementations must embed UnimplementedWarehouseV1Server
// for forward compatibility
type WarehouseV1Server interface {
	Reserve(context.Context, *ReserveRequest) (*ReserveResponse, error)
	UndoReserve(context.Context, *UndoReserveRequest) (*UndoReserveResponse, error)
	Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error)
	mustEmbedUnimplementedWarehouseV1Server()
}

// UnimplementedWarehouseV1Server must be embedded to have forward compatible implementations.
type UnimplementedWarehouseV1Server struct {
}

func (UnimplementedWarehouseV1Server) Reserve(context.Context, *ReserveRequest) (*ReserveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reserve not implemented")
}
func (UnimplementedWarehouseV1Server) UndoReserve(context.Context, *UndoReserveRequest) (*UndoReserveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UndoReserve not implemented")
}
func (UnimplementedWarehouseV1Server) Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedWarehouseV1Server) GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedWarehouseV1Server) mustEmbedUnimplementedWarehouseV1Server() {}

// UnsafeWarehouseV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WarehouseV1Server will
// result in compilation errors.
type UnsafeWarehouseV1Server interface {
	mustEmbedUnimplementedWarehouseV1Server()
}

func RegisterWarehouseV1Server(s grpc.ServiceRegistrar, srv WarehouseV1Server) {
	s.RegisterService(&WarehouseV1_ServiceDesc, srv)
}

func _WarehouseV1_Reserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseV1Server).Reserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/warehouse_v1.WarehouseV1/Reserve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseV1Server).Reserve(ctx, req.(*ReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseV1_UndoReserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndoReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseV1Server).UndoReserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/warehouse_v1.WarehouseV1/UndoReserve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseV1Server).UndoReserve(ctx, req.(*UndoReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseV1_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseV1Server).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/warehouse_v1.WarehouseV1/Release",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseV1Server).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseV1_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseV1Server).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/warehouse_v1.WarehouseV1/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseV1Server).GetAll(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WarehouseV1_ServiceDesc is the grpc.ServiceDesc for WarehouseV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WarehouseV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "warehouse_v1.WarehouseV1",
	HandlerType: (*WarehouseV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reserve",
			Handler:    _WarehouseV1_Reserve_Handler,
		},
		{
			MethodName: "UndoReserve",
			Handler:    _WarehouseV1_UndoReserve_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _WarehouseV1_Release_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _WarehouseV1_GetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "warehouse.proto",
}
